### PR TITLE
Reviewed code for Style tag

### PR DESCRIPTION
**Pull request by ptsavdar**
Here is my new PR, following your remarks here #24. I've also answered to them directly. Thanks for having already merged the Image tag.

### CODE REVIEW

**Comment by JangoBrick** [comment]
Thanks for your work, again. And please excuse the fact that I haven't responded yet. I'm currently busy with another project that has a very strict deadline, but it will be done soon, and I will get back to you ASAP.

**Comment by ptsavdar** [comment]
No problem at all. No need for excuses, I totally understand. No rush at all, really, take your time. Thanks again for reviewing my changes/propositions. Have a nice day.

**Comment by JangoBrick** [comment]
Finally got around to merging this. Thanks for the great contribution :)

**Comment by JangoBrick** [comment]
I'll change a few more things, then push out a new release.

**Pull request merged**
